=head1 Repository used to learn P6

=head2 Terminology used

*.p6 or *.P6 that's the Perl 6 file extensions (P6 stands for Perl 6).

*.pm6 or *.pm for P6 module names (second one is the old version in P5).

=head2 Books used

Several books were used to learnt P6. Usualy that's a *.txt *.pdf file in the repository. May be other types will be added in the future.

=head2 Repository name

MyExos
